#!/usr/bin/env -S uv run --script
# /// script
# dependencies = ["black"]
# ///
"""format code with black"""
import subprocess
import sys

result = subprocess.run(["black", "wormnet", "tests", "wormnet.py"])
sys.exit(result.returncode)
